name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Version to use for release tag
        required: true

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        binary:
          - app
          - pi
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.binary }}
    env:
      BINARY: ${{ matrix.binary }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.14.x

    - name: Set up Pillow
      run: |
        pip install --upgrade pip
        pip install Pillow

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Set up Image Path
      shell: bash
      run: |
        if [[ "$RUNNER_OS" = "Windows" ]]; then
          echo "image_path=images/icon.png;images" >> $GITHUB_ENV
        else
          echo "image_path=images/icon.png:images" >> $GITHUB_ENV
        fi

    - name: Build executable
      shell: bash
      run: |
          pyinstaller --clean -y -n "led-$BINARY" --noconsole --onefile --add-data="$image_path" --icon="images/icon.ico" led-$BINARY.py

    - name: Upload ready files
      uses: actions/upload-artifact@v7
      with:
        name: project-led-${{ matrix.os }}-${{ matrix.binary }}
        path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: project-led-*
          path: dist/*
          merge-multiple: true

      - name: Create release
        run: gh release create "$TAG" --generate-notes dist/*.zip
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.event.inputs.tag }}