name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Version to use for release tag
        required: true

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: led-*.tar
          path: dist
          merge-multiple: true

      - name: Create release
        run: gh release create "$TAG" --generate-notes dist/*
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.event.inputs.tag }}