name: Release

on:
  workflow_dispatch:

jobs:
  publish-py:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.14.x

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Install PortAudio (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev python3-dev

    - name: Install PortAudio (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install portaudio

    - name: Install PortAudio (Windows)
      if: runner.os == 'Windows'
      run: |
        vcpkg install portaudio:x64-windows-static
      shell: bash

    - name: Build PyAudio (Windows)
      if: runner.os == 'Windows'
      run: |
        $env:VCPKG_PATH = "$env:VCPKG_INSTALLATION_ROOT\installed\x64-windows-static"
      shell: pwsh

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller 'led-app.py'
        pyinstaller 'led-pi.py'

    - uses: actions/upload-artifact@v7
      with:
        name: project-led-release-${{ matrix.os }}
        path: install/*